dfxtrain<-read.table("./Getdata/train/X_train.txt", header=TRUE)
dfytrain<-read.table("./Getdata/train/y_train.txt", header=TRUE)
dfstrain<-read.table("./Getdata/train/subject_train.txt", header=TRUE)
dftrain<-cbind.data.frame(dfxtrain, dfytrain,dfstrain)
dfxtest<-read.table("./Getdata/test/X_test.txt", header=TRUE)
dfytest<-read.table("./Getdata/test/y_test.txt", header=TRUE)
dfstest<-read.table("./Getdata/test/subject_test.txt", header=TRUE)
dftest<-cbind.data.frame(dfxtest, dfytest, dfstest)
dfheader<-read.table("./Getdata/test/subject_test.txt", header=TRUE)
